/**
 * Realistic mock data for charts, tables, and dashboards
 */

// Revenue data for MRR chart
export const mrrData = [
  { month: "Jul '25", mrr: 2400, subscribers: 48 },
  { month: "Aug '25", mrr: 4100, subscribers: 82 },
  { month: "Sep '25", mrr: 6800, subscribers: 136 },
  { month: "Oct '25", mrr: 9200, subscribers: 184 },
  { month: "Nov '25", mrr: 12500, subscribers: 250 },
  { month: "Dec '25", mrr: 15800, subscribers: 316 },
  { month: "Jan '26", mrr: 19400, subscribers: 388 },
  { month: "Feb '26", mrr: 24100, subscribers: 482 },
  { month: "Mar '26", mrr: 28900, subscribers: 578 },
  { month: "Apr '26", mrr: 34200, subscribers: 684 },
];

export const revenueByModule = [
  { name: "AI Signals", value: 12400, color: "#00ff88" },
  { name: "Trading Bot", value: 8200, color: "#00d4ff" },
  { name: "Telegram Bot", value: 5800, color: "#ffb800" },
  { name: "Mining Intel", value: 4200, color: "#ff6b6b" },
  { name: "Marketplace", value: 2400, color: "#a855f7" },
  { name: "Data Pipeline", value: 1200, color: "#06b6d4" },
];

export const subscribersByTier = [
  { tier: "Starter ($49)", count: 412, revenue: 20188 },
  { tier: "Pro ($149)", count: 198, revenue: 29502 },
  { tier: "Enterprise ($499)", count: 74, revenue: 36926 },
];

// Telegram data
export const telegramGrowthData = [
  { month: "Oct '25", subscribers: 120 },
  { month: "Nov '25", subscribers: 340 },
  { month: "Dec '25", subscribers: 680 },
  { month: "Jan '26", subscribers: 1250 },
  { month: "Feb '26", subscribers: 2100 },
  { month: "Mar '26", subscribers: 3400 },
  { month: "Apr '26", subscribers: 4800 },
];

export const trendingTopics = [
  {
    topic: "Bitcoin ETF Inflows",
    sentiment: "bullish" as const,
    mentions: 12400,
  },
  {
    topic: "Ethereum Pectra Upgrade",
    sentiment: "bullish" as const,
    mentions: 8900,
  },
  {
    topic: "SOL DeFi TVL Surge",
    sentiment: "bullish" as const,
    mentions: 6200,
  },
  {
    topic: "SEC Crypto Regulation",
    sentiment: "bearish" as const,
    mentions: 5800,
  },
  {
    topic: "Stablecoin Market Cap ATH",
    sentiment: "neutral" as const,
    mentions: 4100,
  },
  {
    topic: "AI x Crypto Narrative",
    sentiment: "bullish" as const,
    mentions: 3800,
  },
];

// Trading bot data
export const tradeHistory = [
  {
    id: 1,
    pair: "BTC/USDT",
    type: "BUY" as const,
    entry: 82450,
    exit: 84200,
    pnl: 2.12,
    timestamp: "2026-04-02 14:32",
  },
  {
    id: 2,
    pair: "ETH/USDT",
    type: "SELL" as const,
    entry: 1920,
    exit: 1875,
    pnl: 2.34,
    timestamp: "2026-04-02 12:15",
  },
  {
    id: 3,
    pair: "SOL/USDT",
    type: "BUY" as const,
    entry: 118.5,
    exit: 125.8,
    pnl: 6.16,
    timestamp: "2026-04-01 22:45",
  },
  {
    id: 4,
    pair: "BNB/USDT",
    type: "SELL" as const,
    entry: 625,
    exit: 612,
    pnl: 2.08,
    timestamp: "2026-04-01 18:20",
  },
  {
    id: 5,
    pair: "BTC/USDT",
    type: "BUY" as const,
    entry: 80100,
    exit: 82450,
    pnl: 2.93,
    timestamp: "2026-04-01 09:10",
  },
  {
    id: 6,
    pair: "AVAX/USDT",
    type: "BUY" as const,
    entry: 20.5,
    exit: 22.8,
    pnl: 11.22,
    timestamp: "2026-03-31 16:40",
  },
  {
    id: 7,
    pair: "ETH/USDT",
    type: "BUY" as const,
    entry: 1850,
    exit: 1920,
    pnl: 3.78,
    timestamp: "2026-03-31 11:25",
  },
  {
    id: 8,
    pair: "SOL/USDT",
    type: "SELL" as const,
    entry: 130,
    exit: 118.5,
    pnl: -8.85,
    timestamp: "2026-03-30 20:15",
  },
];

export const pnlChartData = [
  { day: "Mar 25", pnl: 0, cumulative: 0 },
  { day: "Mar 26", pnl: 120, cumulative: 120 },
  { day: "Mar 27", pnl: -45, cumulative: 75 },
  { day: "Mar 28", pnl: 210, cumulative: 285 },
  { day: "Mar 29", pnl: 85, cumulative: 370 },
  { day: "Mar 30", pnl: -180, cumulative: 190 },
  { day: "Mar 31", pnl: 340, cumulative: 530 },
  { day: "Apr 1", pnl: 195, cumulative: 725 },
  { day: "Apr 2", pnl: 280, cumulative: 1005 },
];

// Mining claims data
export const miningClaims = [
  {
    id: 1,
    name: "Goldstrike Ridge",
    location: "Nevada, USA",
    mineral: "Gold",
    acreage: 160,
    aiScore: 92,
    status: "Active",
    lat: 40.8,
    lng: -117.5,
    premium: false,
  },
  {
    id: 2,
    name: "Silver Creek Basin",
    location: "Colorado, USA",
    mineral: "Silver",
    acreage: 240,
    aiScore: 87,
    status: "Active",
    lat: 39.5,
    lng: -106.0,
    premium: false,
  },
  {
    id: 3,
    name: "Copper Mountain",
    location: "Arizona, USA",
    mineral: "Copper",
    acreage: 320,
    aiScore: 84,
    status: "Pending",
    lat: 34.2,
    lng: -111.3,
    premium: false,
  },
  {
    id: 4,
    name: "Lithium Flats",
    location: "Nevada, USA",
    mineral: "Lithium",
    acreage: 500,
    aiScore: 96,
    status: "Active",
    lat: 38.5,
    lng: -118.2,
    premium: true,
  },
  {
    id: 5,
    name: "Rare Earth Valley",
    location: "Wyoming, USA",
    mineral: "REE",
    acreage: 180,
    aiScore: 78,
    status: "Active",
    lat: 42.8,
    lng: -107.2,
    premium: true,
  },
  {
    id: 6,
    name: "Emerald Point",
    location: "Montana, USA",
    mineral: "Gold",
    acreage: 120,
    aiScore: 71,
    status: "Inactive",
    lat: 46.8,
    lng: -110.3,
    premium: false,
  },
  {
    id: 7,
    name: "Platinum Ridge",
    location: "Oregon, USA",
    mineral: "Platinum",
    acreage: 280,
    aiScore: 89,
    status: "Active",
    lat: 44.0,
    lng: -121.5,
    premium: true,
  },
  {
    id: 8,
    name: "Cobalt Springs",
    location: "Idaho, USA",
    mineral: "Cobalt",
    acreage: 200,
    aiScore: 82,
    status: "Pending",
    lat: 43.6,
    lng: -114.3,
    premium: false,
  },
  {
    id: 9,
    name: "Diamond Creek",
    location: "Arkansas, USA",
    mineral: "Diamond",
    acreage: 90,
    aiScore: 65,
    status: "Active",
    lat: 34.1,
    lng: -93.6,
    premium: false,
  },
  {
    id: 10,
    name: "Tungsten Peak",
    location: "California, USA",
    mineral: "Tungsten",
    acreage: 150,
    aiScore: 76,
    status: "Active",
    lat: 37.8,
    lng: -118.2,
    premium: false,
  },
  {
    id: 11,
    name: "Molybdenum Mesa",
    location: "New Mexico, USA",
    mineral: "Molybdenum",
    acreage: 340,
    aiScore: 88,
    status: "Active",
    lat: 35.6,
    lng: -106.6,
    premium: true,
  },
  {
    id: 12,
    name: "Zinc Hollow",
    location: "Tennessee, USA",
    mineral: "Zinc",
    acreage: 110,
    aiScore: 62,
    status: "Inactive",
    lat: 35.5,
    lng: -85.0,
    premium: false,
  },
  {
    id: 13,
    name: "Uranium Basin",
    location: "Utah, USA",
    mineral: "Uranium",
    acreage: 420,
    aiScore: 91,
    status: "Active",
    lat: 38.5,
    lng: -109.5,
    premium: true,
  },
  {
    id: 14,
    name: "Nickel Ridge",
    location: "Michigan, USA",
    mineral: "Nickel",
    acreage: 190,
    aiScore: 73,
    status: "Pending",
    lat: 46.5,
    lng: -87.4,
    premium: false,
  },
  {
    id: 15,
    name: "Beryllium Bluff",
    location: "South Dakota, USA",
    mineral: "Beryllium",
    acreage: 130,
    aiScore: 68,
    status: "Active",
    lat: 43.9,
    lng: -103.5,
    premium: false,
  },
  {
    id: 16,
    name: "Tantalum Terrace",
    location: "North Carolina, USA",
    mineral: "Tantalum",
    acreage: 170,
    aiScore: 85,
    status: "Active",
    lat: 35.2,
    lng: -82.5,
    premium: true,
  },
  {
    id: 17,
    name: "Vanadium Valley",
    location: "Colorado, USA",
    mineral: "Vanadium",
    acreage: 260,
    aiScore: 79,
    status: "Active",
    lat: 38.3,
    lng: -108.5,
    premium: false,
  },
  {
    id: 18,
    name: "Manganese Meadow",
    location: "Virginia, USA",
    mineral: "Manganese",
    acreage: 140,
    aiScore: 58,
    status: "Inactive",
    lat: 37.4,
    lng: -79.4,
    premium: false,
  },
  {
    id: 19,
    name: "Antimony Arch",
    location: "Alaska, USA",
    mineral: "Antimony",
    acreage: 600,
    aiScore: 94,
    status: "Active",
    lat: 64.8,
    lng: -147.7,
    premium: true,
  },
  {
    id: 20,
    name: "Graphite Gorge",
    location: "Alabama, USA",
    mineral: "Graphite",
    acreage: 210,
    aiScore: 74,
    status: "Pending",
    lat: 33.2,
    lng: -86.8,
    premium: false,
  },
];

// Marketplace services
export const aiServices = [
  {
    id: 1,
    name: "Signal Generation API",
    description:
      "Real-time BUY/SELL/HOLD signals for 200+ crypto pairs with AI confidence scoring. Includes RSI, EMA, MACD analysis.",
    price: "$99/mo",
    category: "Trading",
    features: [
      "200+ pairs",
      "60s refresh",
      "Webhook support",
      "Historical data",
    ],
  },
  {
    id: 2,
    name: "Sentiment Analysis API",
    description:
      "NLP-powered sentiment analysis across Twitter, Reddit, Telegram, and news sources. Bullish/bearish scoring in real-time.",
    price: "$79/mo",
    category: "Analytics",
    features: ["4 data sources", "Real-time", "Trend detection", "API access"],
  },
  {
    id: 3,
    name: "Claim Scoring API",
    description:
      "AI-powered mining and land claim evaluation. Geological data analysis, mineral probability scoring, and risk assessment.",
    price: "$149/mo",
    category: "Mining",
    features: [
      "Geological AI",
      "Risk scoring",
      "Satellite data",
      "PDF reports",
    ],
  },
  {
    id: 4,
    name: "Content Generation",
    description:
      "Automated crypto market reports, newsletter generation, and social media content creation powered by GPT-4 fine-tuned models.",
    price: "$49/mo",
    category: "Content",
    features: [
      "Daily reports",
      "Newsletter",
      "Social posts",
      "Custom templates",
    ],
  },
  {
    id: 5,
    name: "Data Pipeline Automation",
    description:
      "Automated data collection, cleaning, and analysis pipelines. Connect CoinGecko, on-chain data, and custom sources.",
    price: "$199/mo",
    category: "Infrastructure",
    features: ["10+ sources", "Auto-ETL", "Custom pipelines", "Alerts"],
  },
  {
    id: 6,
    name: "Custom Bot Development",
    description:
      "Bespoke trading bot development with your strategy. Includes backtesting, deployment, and 30 days of monitoring.",
    price: "$999 one-time",
    category: "Development",
    features: [
      "Custom strategy",
      "Backtesting",
      "Deployment",
      "30-day support",
    ],
  },
];
